config/routes.rb
Rails.application.routes.draw do
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
      # config/routes.rb
      # Setting up the landing page
    root 'students#index'
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
    # app/models/student.rb

    class Student < ApplicationRecord
      after_commit :notify_pusher, on: [:create, :update]

      def notify_pusher
        Pusher.trigger('student', 'new', self.as_json)
      end
    end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
    @student = Student.new # add this line # SINGULAR FORM
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :corporation, :session, :transport, :date, :check)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
        <%# app/views/layouts/application.html.erb %>
  <head>
    <title>Agenda Mensual de Mile Peña ***CSDD***</title>
    <%= csrf_meta_tags %>
<!--     <%= csp_meta_tag %> -->
    
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://js.pusher.com/4.1/pusher.min.js"></script> <!-- # add this line -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student, remote: true, format: :json, id: 'add_student') do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :student_name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :corporation %>
    <%= form.select :corporation, [['Lunes', 'Lunes'], ['Martes', 'Martes',], ['Miércoles', 'Miércoles'], ['Jueves', 'Jueves'], ['Viernes', 'Viernes']], {}, { class: "form-control", id: "student_corporation" } %>    
  </div>

  <div class="field">
    <%= form.label :session %>
    <%= form.text_field :session, id: :student_session, class: "form-control" %>    
  </div>

  <div class="field">
    <%= form.label :transport %>
    <%= form.text_field :transport, id: :student_transport, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date, id: :student_date, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :check %>
    <%= form.text_field :check, id: :student_check, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Student', class: "btn btn-success" %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
    <%# app/views/students/index.html.erb %>

    <div class='container-fluid'>
      <p id="notice"><%= notice %></p>
      <div class='row py-3 px-3'>
        <div class='col-12 col-sm-8'>
          <h3 class=''>Agenda Mensual de Mile Peña</h3>
          <table id='student-table' class="table table-hover">
            <thead  class="thead-light">
              <tr>
                <th>Name</th>
                <th>Corporation</th>
                <th>Session</th>
                <th>Transport</th>
                <th>Date</th>
                <th>Check</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @students.each do |student| %>
                <tr>
                  <td><%= student.name %></td>
                  <td><%= student.corporation %></td>
                  <td><%= student.session %></td>
                  <td><%= student.transport %></td>
                  <td><%= student.date %></td>
                  <td><%= student.check %></td>
                  <td><%= link_to 'Show', student %></td>
                  <td><%= link_to 'Edit', edit_student_path(student) %></td>
                  <td><%= link_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <br>
        </div>

        <div class='col-12 col-sm-4'>
          <h3>New Student</h3>
          <%= render 'form', student: @student %>
        </div>
      </div>
    </div>

<!-- <%= link_to 'New Student', new_student_path %> -->

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Corporation:</strong>
  <%= @student.corporation %>
</p>

<p>
  <strong>Session:</strong>
  <%= @student.session %>
</p>

<p>
  <strong>Transport:</strong>
  <%= @student.transport %>
</p>

<p>
  <strong>Date:</strong>
  <%= @student.date %>
</p>

<p>
  <strong>Check:</strong>
  <%= @student.check %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>